require("plugins.packer")
require("plugins.tree")
require("plugins.rosepine")
require("plugins.harpoon")
require("plugins.comment")
require("plugins.lsp")
require("plugins.nonels")
require("plugins.lualine")
