require("plugins.packer")
require("plugins.tree")
--require("plugins.synthwave")
require("plugins.rosepine")
require("plugins.harpoon")
require("plugins.comment")
require("plugins.lualine")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.fugitive")
require("plugins.telescope")
require("plugins.lspsaga")
require("plugins.clipboard")
require("plugins.lazydocker")
-- require("plugins.vimspector")
require("plugins.dadbod")
