require("plugins.packer")
require("plugins.tree")
require("plugins.rosepine")
require("plugins.harpoon")
require("plugins.comment")
require("plugins.lualine")
require("plugins.lsp")
require("plugins.cmp")
require("mason").setup()

